swagger: "2.0"
info:
  description: "API to process CSV and recommend products for promotion using AI."
  version: "1.0.0"
  title: "Promotion AI API"
host: "localhost:5000"
basePath: "/"
tags:
  - name: "Promotion API"
    description: "Endpoints for generating product promotions"
schemes:
  - "http"
paths:
  /upload_csv:
    post:
      tags:
        - "Promotion API"
      summary: "Upload CSV and return products for promotion"
      description: "Processes a CSV file and identifies products suitable for promotion."
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - name: "file"
          in: "formData"
          description: "CSV file with product data"
          required: true
          type: "file"
      responses:
        200:
          description: "List of products selected for promotion"
          schema:
            type: "array"
            items:
              type: "string"
        400:
          description: "Bad Request - Missing required columns or invalid data"
        500:
          description: "Internal Server Error"
