swagger: "2.0"
info:
  title: API de Promoción de Productos
  description: Endpoint para seleccionar productos para una promoción basándose en clustering de productos.
  version: "1.0.0"
paths:
  /api/promocion:
    post:
      summary: Seleccionar productos para la promoción
      parameters:
        - name: file
          in: formData
          type: file
          required: true
          description: Archivo CSV con la información de los productos
      responses:
        200:
          description: Productos seleccionados para la promoción
          schema:
            type: object
            properties:
              productos:
                type: array
                items:
                  type: string
        400:
          description: Error de archivo no válido
